### ISSUE TITLE
Hyperlinks in HTML must use system URLs, not PIDs

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez-ui#121]
The _has narrower_ values for a Concept, such as `Cenozoic` for `Phanerozoic` use the PIDs for the hyperlinks in HTML. This means when a PID redirects to a system that is not this VocPrez, the user will go elsewhere instead of staying on this system.

e.g., for for `Phanerozoic` at https://vocabulary.gswa.kurrawong.ai/v/vocab/ics:ischart/schrt:Phanerozoic, click on `Cenozoic` and you go to [ARDC's Cenozoic](https://vocabs.ardc.edu.au/repository/api/lda/csiro/international-chronostratigraphic-chart/geologic-time-scale-2020/resource?uri=http://resource.geosciml.org/classifier/ics/ischart/Cenozoic) following a redirect from <http://resource.geosciml.org/classifier/ics/ischart/Cenozoic>. We should be going to <https://vocabulary.gswa.kurrawong.ai/v/vocab/ics:ischart/schrt:Cenozoic>.

VocPrez needs to be 'jealous' and hog all links, redirecting them internally. There should be an option to got to the PID location, so when we have an external PID for a link, we might need a [->] icon next to the link for the PID location - the standard external web link icon.

If internal links are used, can they be fast like other Vue links that don't do a full page reload?

**Comment by nicholascar** [comment]
This does seem to be working correctly within Collections, see https://vocabulary.gswa.kurrawong.ai/v/collection/schrt:Ages

**Comment by recalcitrantsupplant** [comment]
FE use single pattern for where prez:links are present - prefer these over URIs

**Comment by hjohns** [comment]
FE to use prez:links over URIs and use internal routing.
