### ISSUE TITLE
Global search not working in Prez nav bar

### ISSUE THREAD

**Issue by edmondchuc** [RDFLib/prez-ui#29]
The Prez global search is not working. There appears to be two issues:

1. When typing a term into the global search bar and pressing enter, it goes to the "Advanced Search" (`/search`) on the client, but no requests are sent to the server. The end result is we land on `/search` with some query params tacked on the URL but no results on the page.
2. Typing a term into the global search bar, the query params tacked on are, `filter` and `searchType`. When in `/search`, when I search for something, the query params are `term` and `method`.

**Comment by jamiefeiss** [comment]
Fixed in a554218
