### ISSUE TITLE
Pagination not working on spatial features

### ISSUE THREAD

**Issue by recalcitrantsupplant** [RDFLib/prez-ui#30]
https://gsq-prez.dev.kurrawong.ai/s/datasets/dtst:qldgeofeatures/collections/qldgftrs:features/items

prez:count 151 is provided

I have created an issue for prez to specify what the default page size is for an endpoint. https://github.com/RDFLib/prez/issues/85 In the interim it can be set to 20 globally

**Comment by jamiefeiss** [comment]
Pagination is now implemented in https://github.com/RDFLib/prez-ui/commit/0a93cfd72ee2777b36c20a8877467da98363559f
