### ISSUE TITLE
SPARQL results not cleared for new search

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez-ui#51]
Using the demo PrezUI instance at https://data.idnau.org/sparql:

If I run a query that returns 35 results, e.g.

```
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT * WHERE {
  GRAPH ?g {
  ?c a skos:Concept ;
     skos:inScheme <https://data.idnau.org/pid/vocab/idn-th> ;
     skos:prefLabel ?pl
  }
}
ORDER BY ?pl
```

and then if I run it again, I get 70 results, then 105, 140 etc.

So the results from previous queries need clearing.

**Comment by jamiefeiss** [comment]
Upon some testing, this might be a backend issue. I'm getting around 3 times as many results as I expect (perhaps one set per subsystem i.e. CatPrez, SpacePrez & VocPrez), and the results accumulate for each follow-up request. The IDN Agents DB UI is also experiencing this issue if pointed to the IDN Prez API.

@recalcitrantsupplant are you able to take a look at this issue?

**Comment by edmondchuc** [comment]
I believe it is a backend issue. Here is the reported issue in Prez https://github.com/RDFLib/prez/issues/76.

**Comment by recalcitrantsupplant** [comment]
See https://github.com/RDFLib/prez/pull/112
