### ISSUE TITLE
Update SPARQL page available endpoints

### ISSUE THREAD

**Issue by edmondchuc** [RDFLib/prez-ui#75]
As a result of https://github.com/RDFLib/prez/pull/127, Prez now only manages one SPARQL endpoint. We should remove the different Prez SPARQL endpoints for each subsystem, as they are all the same now.

<img width="946" alt="Screenshot 2023-06-22 at 11 22 50 am" src="https://github.com/RDFLib/prez-ui/assets/37032744/1e677374-a6ff-4abb-9e71-48c09d2610da">

**Comment by hjohns** [comment]
CatPrez and SpacePrez searches that use a specific subsystem SPARQL endpoint also need updating.
