### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by RichDijk** [RDFLib/prez-ui#91]
Hi,

I want to try prez-ui en have downloaded the sources.
Followed by:
   npm install
   npm run build

gives: 
E:\prez\prez-ui-3.5.0>npm run build

> prez-ui@3.0.1 build E:\prez\prez-ui-3.5.0
> run-p type-check build-only; shx cp dist/index.html dist/404.html

ERROR: Task not found: "build-only;", shx", cp", dist/index.html", dist/404.html"
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prez-ui@3.0.1 build: `run-p type-check build-only; shx cp dist/index.html dist/404.html`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prez-ui@3.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\richa\AppData\Roaming\npm-cache\_logs\2023-08-11T13_27_23_417Z-debug.log

What is going wrong?
regards, Richard

**Comment by edmondchuc** [comment]
Thanks for the report @RichDijk. I can see you're running the build task on Windows. I just tested it on my Windows machine and can confirm the issue. It works fine on macOS and Linux.

The issue is on Windows, it interprets `build-only;` with the semicolon as part of the command, rather than as a separator for commands like on macOS and Linux.

I've created a PR to fix it here https://github.com/RDFLib/prez-ui/pull/92.

In the meantime, you can edit your local copy of `package.json` and make the following change.

```diff
{
    "name": "prez-ui",
    "version": "3.0.1",
    "private": true,
    "scripts": {
        "dev": "vite",
--        "build": "run-p type-check build-only; shx cp dist/index.html dist/404.html",
++        "build": "run-p type-check build-only && shx cp dist/index.html dist/404.html",
        "preview": "vite preview",
        "test:unit": "vitest --environment jsdom --root src/",
        "build-only": "vite build",
        "type-check": "vue-tsc --noEmit -p tsconfig.vitest.json --composite false"
    },
    "dependencies": {
        "@fawmi/vue-google-maps": "^0.9.79",
        "@terraformer/arcgis": "^2.1.2",
        "@terraformer/wkt": "^2.1.2",
        "@triply/yasqe": "^4.2.28",
        "@triply/yasr": "^4.2.28",
        "axios": "^1.3.4",
        "n3": "^1.16.3",
        "pinia": "^2.0.26",
        "vite-plugin-rewrite-all": "^1.0.1",
        "vue": "^3.2.45",
        "vue-router": "^4.1.6"
    },
    "devDependencies": {
        "@types/google.maps": "^3.52.3",
        "@types/jsdom": "^20.0.1",
        "@types/n3": "^1.10.4",
        "@types/node": "^18.11.9",
        "@types/terraformer__arcgis": "^2.0.2",
        "@vitejs/plugin-vue": "^3.2.0",
        "@vue/test-utils": "^2.2.4",
        "@vue/tsconfig": "^0.1.3",
        "events": "^3.3.0",
        "jsdom": "^20.0.3",
        "npm-run-all": "^4.1.5",
        "sass": "^1.55.0",
        "shx": "^0.3.4",
        "typescript": "~4.7.4",
        "vite": "^3.2.4",
        "vite-plugin-vue-type-imports": "^0.2.4",
        "vitest": "^0.25.3",
        "vue-tsc": "^1.0.9"
    }
}

```

**Comment by RichDijk** [comment]
Thank you that works :)

prez-ui is running, next is prez configuration en data loading in  Fuseki.

**Comment by edmondchuc** [comment]
If you are familiar with Docker, there's a [`docker-compose.yml`](https://github.com/RDFLib/prez/blob/main/demo/docker-compose.yml) which you can use as a starting point.
