### ISSUE TITLE
Breadcrumb labels

### ISSUE THREAD

**Issue by hjohns** [RDFLib/prez-ui#97]
Breadcrumbs become generalised as you go deeper into a vocab.

E.g:
1. Start from Borehold Start Point vocab page:
     Home > Vocabularies Home > Vocabularies > Borehole Start Point

2. Click on Offshore concept: (Breadcrumb loses Borehole Start Point)
     Home > Vocabularies Home > Vocabularies > Vocabulary > Offshore

**Comment by recalcitrantsupplant** [comment]
confirm relevant labels are being returned from BE and add to breadcrumbs
